workspace:
    base: /go
    path: src/github.com/banzaicloud/pipeline

pipeline:
    create_cluster:
        image: banzaicloud/ci-pipeline-client:latest
        action: CreateCluster
        secret:
            name: my-kubernetes-secret-444
        cluster:
            cloud: kubernetes
            distribution: unknown
            location: unknown
            name: kubernetes-ecsy-464
            reuse: true
            installsecrets: true

    build:
        image: golang:1.11.1
        commands:
            - make vendor build
        secretFrom:
            my_username:
                name: my-password-secret-518
                keyRef: username
            my_password:
                name: my-password-secret-518
                keyRef: password

    test:
        image: golang:1.11.1
        commands:
            - mkdir $HOME/config
            - cp config/config.toml.example $HOME/config/config.toml
            - make test
        environment:
            VAULT_ADDR: http://vault:8200
            VAULT_TOKEN: 227e1cce-6bf7-30bb-2d2a-acc854318caf

    build_container:
        image: plugins/docker
        dockerfile: Dockerfile
        repo: banzaicloud/pipeline
        tags: '{{ printf "%s" .DRONE_BRANCH }}'
        log: debug

services:
    vault:
        image: vault:0.10.4
        ports:
            - 8200
        environment:
            SKIP_SETCAP: "true"
            VAULT_DEV_ROOT_TOKEN_ID: 227e1cce-6bf7-30bb-2d2a-acc854318caf
